# import requests
import os
import fitz
from pathlib import Path

# write a function that detects file type


def convert_pdf_to_txt(pdf_file):
    doc = fitz.open(pdf_file)
    text = ""
    for page in doc:
        text+=page.get_text()
        # print(text)
    with open(f'{file_name}.txt', 'a') as f:
        f.write(text)
        f.close()

pdf_file = 'resume2023v2.pdf'
file_name=Path(pdf_file).stem
convert_pdf_to_txt(pdf_file)

# url = 'https://pdftotext.com/'

# pdf_file = 'resume2023v2.pdf'

# response = requests.post(url, files={'file': open(pdf_file, 'rb')})

# if response.status_code == 200:
#     with open(os.path.splitext(pdf_file)[0] + '.txt', 'wb') as f:
#         f.write(response.content)
#         f.close()
#         print('File saved as:', os.path.splitext(pdf_file)[0] + '.txt')
#         with open(f'{pdf_file}_autogenerated.txt', 'a') as f:
#             f.write(pdf_file + ' ' + os.path.splitext(pdf_file)[0] + '.txt' + '\n')
#             f.close()
