import requests
import os

url = 'https://pdftotext.com/'

pdf_file = 'resume2023v2.pdf'

response = requests.post(url, files={'file': open(pdf_file, 'rb')})

if response.status_code == 200:
    with open(os.path.splitext(pdf_file)[0] + '.txt', 'wb') as f:
        f.write(response.content)
        f.close()
        print('File saved as:', os.path.splitext(pdf_file)[0] + '.txt')
        with open(f'{pdf_file}_autogenerated.txt', 'a') as f:
            f.write(pdf_file + ' ' + os.path.splitext(pdf_file)[0] + '.txt' + '\n')
            f.close()
